
"Host(\"zenithos.org\");\n";
Host("zenithos.org");
"Host(\"duckduckgo.com\");\n";
Host("duckduckgo.com");
"Host(\"bitchute.com\");\n";
Host("bitchute.com");
"Host(\"github.com\");\n";
Host("github.com");
"Host(\"soundcloud.com\");\n";
Host("soundcloud.com");
"Host(\"wiki.osdev.org\");\n";
Host("wiki.osdev.org");
"Host(\"archive.org\");\n";
Host("archive.org");
"Host(\"git.checksum.fail\");\n";
Host("git.checksum.fail");

DNSRep;
ARPRep;