Cd(__DIR__);;
#include "Math"
#include "MathODE"

Option(OPTf_WARN_PAREN, ON);
Option(OPTf_WARN_DUP_TYPES, ON);
Option(OPTf_WARN_UNUSED_VAR, OFF);	// Assembly pulls args from the stack
									// instead of using argument identifiers.
#include "Types"
#include "Conversion"
#include "F32"
#include "Vec4"
#include "Vec3"
#include "Mat4"

#define HOLYMATH_COMPILED

Option(OPTf_WARN_UNUSED_VAR, ON);

Cd("..");;