Cd(__DIR__);;

#include "GrInitA"
#include "Gr.HH"
#include "GrExterns"
#include "GrGlobals"
#include "GrTextBase"
#include "GrAsm"
#include "GrPalette"
#include "GrDC"
#include "GrInitB"
#include "GrMath"
#include "GrScreen"
#include "GrBitMap"
#include "GrPrimatives"
#include "GrComposites"
#include "ScreenCast"

#define SPE_ABORT 	(-1)
#define SPE_EXIT	0
#define SPE_CONT	1
#include "SpriteNew"
#include "GrSpritePlot"
#include "SpriteMesh"
#include "SpriteBitMap"
#include "SpriteCode"
#include "SpriteSideBar"
#include "SpriteEd"
#include "SpriteMain"

#include "GrEnd"

Cd("..");;
