Cd(__DIR__);;

//If these are not present in /Home, it uses the version in the root dir.  You
//can make your own, modified, version of these files in your /Home directory.
#include "~/03-HomeLocalize"
#include "/System/Boot/MakeBoot"
#include "/System/Utils/MakeUtils"
#include "~/04-HomeWrappers"
MapFileLoad("::/Kernel/Kernel");
MapFileLoad("::/Compiler/Compiler");
#include "~/05-HomeKeyPlugIns"
#include "~/06-HomeSys"
Cd("..");;
